export const BookData = [
  {
    id: 1,
    year: '2022',
    title: 'Batch 2022',
    action: 'true',
  },
  {
    id: 2,
    year: '2021',
    title: 'Batch 2021',
    action: 'true',
  },
  {
    id: 3,
    year: '2020',
    title: 'Batch 2020',
    action: 'true',
  },
  {
    id: 4,
    year: '2019',
    title: 'Batch 2019',
    action: 'true',
  },
  {
    id: 5,
    year: '2018',
    title: 'Batch 2018',
    action: 'true',
  },
];

export const ClientData = [
  {
    id: 1,
    url: 'https://www.kindpng.com/picc/m/702-7024753_monkey-d-luffy-hat-png-download-monkey-d.png',
    name: 'Monkey D. Luffy',
    address: 'Baliwasan, Zamboanga City',
    sex: 'Male',
    section: 'Sampaguita',
    qoute: 'If you are hungry, Eat.',
    action: true,
  },
  {
    id: 2,
    url: 'https://www.kindpng.com/picc/m/702-7024753_monkey-d-luffy-hat-png-download-monkey-d.png',
    name: 'Monkey D. Luffy',
    address: 'Baliwasan, Zamboanga City',
    sex: 'Male',
    section: 'Sampaguita',
    qoute: 'If you are hungry, Eat.',
    action: true,
  },
  {
    id: 3,
    url: 'https://www.kindpng.com/picc/m/702-7024753_monkey-d-luffy-hat-png-download-monkey-d.png',
    name: 'Monkey D. Luffy',
    address: 'Baliwasan, Zamboanga City',
    sex: 'Male',
    section: 'Sampaguita',
    qoute: 'If you are hungry, Eat.',
    action: true,
  },
  {
    id: 4,
    url: 'https://www.kindpng.com/picc/m/702-7024753_monkey-d-luffy-hat-png-download-monkey-d.png',
    name: 'Monkey D. Luffy',
    address: 'Baliwasan, Zamboanga City',
    sex: 'Male',
    section: 'Sampaguita',
    qoute: 'If you are hungry, Eat.',
    action: true,
  },
  {
    id: 5,
    url: 'https://www.kindpng.com/picc/m/702-7024753_monkey-d-luffy-hat-png-download-monkey-d.png',
    name: 'Monkey D. Luffy',
    address: 'Baliwasan, Zamboanga City',
    sex: 'Male',
    section: 'Sampaguita',
    qoute: 'If you are hungry, Eat.',
    action: true,
  },
  {
    id: 6,
    url: 'https://www.kindpng.com/picc/m/702-7024753_monkey-d-luffy-hat-png-download-monkey-d.png',
    name: 'Monkey D. Luffy',
    address: 'Baliwasan, Zamboanga City',
    sex: 'Male',
    section: 'Sampaguita',
    qoute: 'If you are hungry, Eat.',
    action: true,
  },
  {
    id: 7,
    url: 'https://www.kindpng.com/picc/m/702-7024753_monkey-d-luffy-hat-png-download-monkey-d.png',
    name: 'Monkey D. Luffy',
    address: 'Baliwasan, Zamboanga City',
    sex: 'Male',
    section: 'Sampaguita',
    qoute: 'If you are hungry, Eat.',
    action: true,
  },
  {
    id: 8,
    url: 'https://www.kindpng.com/picc/m/702-7024753_monkey-d-luffy-hat-png-download-monkey-d.png',
    name: 'Monkey D. Luffy',
    address: 'Baliwasan, Zamboanga City',
    sex: 'Male',
    section: 'Sampaguita',
    qoute: 'If you are hungry, Eat.',
    action: true,
  },
  {
    id: 9,
    url: 'https://www.kindpng.com/picc/m/702-7024753_monkey-d-luffy-hat-png-download-monkey-d.png',
    name: 'Monkey D. Luffy',
    address: 'Baliwasan, Zamboanga City',
    sex: 'Male',
    section: 'Sampaguita',
    qoute: 'If you are hungry, Eat.',
    action: true,
  },
  {
    id: 10,
    url: 'https://www.kindpng.com/picc/m/702-7024753_monkey-d-luffy-hat-png-download-monkey-d.png',
    name: 'Monkey D. Luffy',
    address: 'Baliwasan, Zamboanga City',
    sex: 'Male',
    section: 'Sampaguita',
    qoute: 'If you are hungry, Eat.',
    action: true,
  },
];

export const InstructorData = [
  {
    id: 1,
    name: 'Rayleigh D. King',
    address: 'Sabaody',
    sex: 'Male',
    action: true,
  },
  {
    id: 2,
    name: 'Rayleigh D. King',
    address: 'Sabaody',
    sex: 'Male',
    action: true,
  },
  {
    id: 3,
    name: 'Rayleigh D. King',
    address: 'Sabaody',
    sex: 'Male',
    action: true,
  },
  {
    id: 4,
    name: 'Rayleigh D. King',
    address: 'Sabaody',
    sex: 'Male',
    action: true,
  },
  {
    id: 5,
    name: 'Rayleigh D. King',
    address: 'Sabaody',
    sex: 'Male',
    action: true,
  },
];

export const SectionData = [
  {
    id: 1,
    name: 'SAMPAGUITA',
    instructor: InstructorData[0].name,
    action: 'true',
  },
  {
    id: 2,
    name: 'SAMPAGUITA',
    instructor: InstructorData[0].name,
    action: 'true',
  },
  {
    id: 3,
    name: 'SAMPAGUITA',
    instructor: InstructorData[0].name,
    action: 'true',
  },
  {
    id: 4,
    name: 'SAMPAGUITA',
    instructor: InstructorData[0].name,
    action: 'true',
  },
  {
    id: 5,
    name: 'SAMPAGUITA',
    instructor: InstructorData[0].name,
    action: 'true',
  },
];

export const UserData = [
  {
    id: 1,
    url: 'https://www.kindpng.com/picc/m/702-7024753_monkey-d-luffy-hat-png-download-monkey-d.png',
    name: 'Mongkey D. Luffy',
    role: 'Super Admin',
    action: true,
  },
  {
    id: 2,
    url: 'https://www.geekmi.news/__export/1657380923276/sites/debate/img/2022/07/09/zoro5.jpg_1103262657.jpg',
    name: 'Roronoa Zoro',
    role: 'Admin',
    action: true,
  },
  {
    id: 3,
    url: 'http://pm1.narvii.com/7206/9461f4ae413e177d710ac02b3cb9a836b578a457r1-821-515v2_uhq.jpg',
    name: 'Vinsmoke Sanji',
    role: 'Admin',
    action: true,
  },
  {
    id: 1,
    url: 'https://qph.cf2.quoracdn.net/main-qimg-a1e8f69ca6140981338015c818fec130-pjlq',
    name: 'Cat Burglar Nami',
    role: 'Client',
    action: true,
  },
  {
    id: 1,
    url: 'https://i1.sndcdn.com/artworks-000064582430-gaygse-t500x500.jpg',
    name: 'Sogeking Ussop',
    role: 'User',
    action: true,
  },
];
